version: "2"
services:
  # App backend service
  back-end:
    # Configuration for building the docker image for the backend service
    build:
      context: back-end # Use an image built from the specified dockerfile in the `app-server` directory.
      dockerfile: Dockerfile # Specify the Dockerfile path
    ports:
      - "8080:8080" # Forward the exposed port 8080 on the container (docker) to port 8080 on the host machine
    restart: always
    depends_on:
      - db # This service depends on mysql. Start that first.
    environment: # Pass environment variables to the service
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/db?useUnicode=true&characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC&createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    networks: # Networks to join (Services on the same network can communicate with each other using their name and no need of address)
      - backend
      - frontend

  # front-end service
  front-end:
    build: ./front-end
    ports:
      - 80:80
    environment:
      NODE_ENV: production
    restart: always
    depends_on:
      - server
    networks:
      - frontend
  
  # Database Service (mysql)
  db:
    image: mysql:5.6
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_DATABASE: db
      MYSQL_USER: root
      MYSQL_PASSWORD: roor
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: "%"
    volumes: # volumes could help in case we lost stored data (it persist data in host machine in the db-data directory)
      - db-data:/var/lib/mysql
    networks:
      - backend
  
# Define Volumes to be created
volumes:
  db-data:
  
# Define Networks to be created to facilitate communication between containers
networks:
  backend:
    driver: bridge
  frontend:
    driver: bridge
