# stage 1 Run build for react app 
FROM node:12.18.0 as build
WORKDIR /app
ENV PATH /app/node_modules/.bin:$PATH
COPY . /app
RUN npm i
RUN npm run build

# stage 2 Copy from the built bundle app to Nginx public directory
FROM nginx:1.19.10
COPY --from=build /app/build /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]